source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'

target 'AGL' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AGL
  pod 'AFNetworking', '~> 3.0'

  target 'AGLTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AGLUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
